server:
  port: 5555

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: true

spring:
  application:
    name: gateway-mcs
  cloud:
    gateway:
      routes:   # видимо, маршруты обрабатываются в порядке их описания в этом файле
        - id: product-mcs
          uri: lb://product-mcs # по аналогии с @LoadBalanced-бином в HystrixApp (см.hystrix-client)
          predicates:           # предикат — это объект, который проверяет, соблюдается ли условие
            - Path=/product-mcs/**
          filters:
            - StripPrefix=1 # удаляем одно звено слева из ?Path?; этим звеном является «/product-mcs»
                            # (подробности : https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-stripprefix-gatewayfilter-factory)
        - id: front-mcs
          uri: lb://front-mcs
          predicates:
            - Path=/**
